# ==================== Where To Install Things ===========================

# The default location for installation.  Everything is placed in
# subdirectories of this directory.  The default values for many of
# the variables below are expressed in terms of this one, so you may
# not need to change them.  This defaults to /usr/local.
prefix=/usr/local

# Like `prefix', but used for architecture-specific files.
exec_prefix=${prefix}

# Where to install oo2c and other binaries that people will want to
# run directly.
bindir=${exec_prefix}/bin

# Where to install shared and static library files.  This directory
# should be in the linker's search path.
libdir=${exec_prefix}/lib

# Where to install other files needed to run oo2c, like symbol files.
oocdir=${exec_prefix}/lib/oo2c

# Where to install oo2c's man pages, and what extension they should have.
mandir=${prefix}/share/man/man1
manext=.1

# ==================== Utility Programs for the Build ====================

# Allow the user to specify the install program.
INSTALL=/usr/bin/install -c
INSTALL_PROGRAM=${INSTALL}
INSTALL_SCRIPT=${INSTALL}
INSTALL_DATA=${INSTALL} -m 644

# ========================================================================

export OOC=bin/oo2c --config oo2crc-install.xml
export OOEF=bin/ooef
export DIFF=/usr/bin/diff
export XSLTPROC=no
export PERL=/usr/bin/perl

export CC=gcc -m32
export CFLAGS=-g -O2
export CPPFLAGS=
export LDFLAGS=
export LIBS=-lm -lgc -ldl 

PACKAGE_VERSION=2.1.11
DISTDIR=oo2c_32-$(PACKAGE_VERSION)
OFLAGS=

PRINT=@echo
MKDIR=mkdir -p -m 755
RM=rm -f
RM_R=rm -Rf
LN_S=ln -s
